runtime: python312

entrypoint: gunicorn -w 2 -b :8080 -k uvicorn.workers.UvicornWorker --log-level debug main:api

instance_class: F1
automatic_scaling:
  min_instances: 1
  max_instances: 1

inbound_services:
  - warmup
